### ISSUE TITLE
gradle import  does not work with windows

### ISSUE THREAD

**Issue by sthiessen23** [GRaViTY-Tool/gravity-tool#10]
In the class org.gravity.eclipse.importer.gradle.GradleBuild the createBuildProcess method does not seem to work under windows.

I always get the error 

> java cannot run program error=2 no such file or directory

Problematic code is this: `case WINDOWS:
			process = Runtime.getRuntime().exec(new String[] {"cmd /c gradlew " , buildTarget}, null, path);
			break;`

I think the first value of the String array can't include the /c gradlew option, it should just be cmd (`new String[] {"cmd", " /c gradlew " , buildTarget}`)

**Comment by SvenPeldszus** [comment]
Fixed with  #741d0c1 and #5bc8ac5
